<?php

/**
 * @file
 * Janrain Capture Admin Screens Module
 */

/**
 * Implements hook_menu_alter().
 */
function janrain_capture_admin_screens_menu_alter(&$items) {
  $items['admin/config/people/janrain_capture/screens'] = array(
    'title' => 'Screens',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('janrain_capture_screens_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -40,
    'file' => drupal_get_path('module', 'janrain_capture_admin_screens') . "/janrain_capture_admin_screens.admin.inc",
  );
}